name: Compilar Lampiao Hidden

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Extrair projeto
        run: |
          rm -rf projeto
          mkdir projeto
          unzip -q lampiao-hidden-1.21.11-completo.zip -d projeto

      - name: Corrigir Fabric Loom
        run: |
          cd projeto
          sed -i "s/id 'fabric-loom-remap'/id 'net.fabricmc.fabric-loom-remap'/" build.gradle

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.6.1'

      - name: Compilar
        run: |
          cd projeto
          gradle build --no-daemon

      - name: Enviar JAR
        uses: actions/upload-artifact@v4
        with:
          name: lampiao-hidden
          path: projeto/build/libs/*.jar
